### PR TITLE
Nix: add flake

### PR DESCRIPTION
**Pull request by GTrunSec**

### CODE REVIEW

**Comment by GTrunSec** [comment]
@NobbZ @adisbladis  please, check it. Thanks.

**Comment by NobbZ** [comment]
In my opinion adding `devshell.toml` is not a flake related change and should be done in another PR, if at all.

Beyond that, this PR lacks information about how to use the flake.

**Comment by GTrunSec** [comment]
> In my opinion adding `devshell.toml` is not a flake related change and should be done in another PR, if at all.

it makes sense,  we can use the option of `--impure` to pass-thru the local environment such as `${./.}` instead of `$DEVSHELL_ROOT`

**Comment by NobbZ** [comment]
That is something I do not understand. So far I never needed `--impure` for anything than allowing `unfree` for a `nix shell`.

And as I am also not using numtides dev-shell, I do not really know what `DEVSHELL_ROOT` would do.

**Pull request closed without merging**
